<?php
  $page = $_REQUEST['p'];
  $arr = [
       array("id"=>'梁冠英 国画 山水画 水墨写意 钰茗阁主 山清水秀 田园 横幅',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu1.jpg"),
       array("id"=>'邹湘溪 国画 山水画 水墨写意 雪 斗方',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu2.jpg"),
       array("id"=>'靳翰龙 国画 山水画 水墨写意 清远 黄湾山人 骆驼 横幅',"title"=>"￥22400.00","pic"=>"assets/images/category-img/pubu3.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu4.jpg"),
       array("id"=>'刘粱经 国画 山水画 水墨写意 集云堂主人 山水 树木 房屋 斗方',"title"=>"￥24000.00","pic"=>"assets/images/category-img/pubu5.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥12000.00","pic"=>"assets/images/category-img/pubu6.jpg"),
       array("id"=>'刘粱经 国画 山水画 水墨写意 集云堂主人 山水 树木 房屋 斗方',"title"=>"￥52000.00","pic"=>"assets/images/category-img/pubu7.jpg"),
       array("id"=>'刘显辰 国画 山水画 水墨写意 青绿山水 人物 斗方',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu8.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 房屋 桥 斗方',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu9.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu10.jpg"),
       array("id"=>'吴延风',"title"=>"￥4900.00","pic"=>"assets/images/category-img/pubu11.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu12.jpg"),
       array("id"=>'梁冠英 国画 山水画 水墨写意 钰茗阁主 山清水秀 田园 横幅',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu13.jpg"),
       array("id"=>'贾少波 国画 山水画 水墨写意 山水 树木 房屋 船 斗方',"title"=>"￥24000","pic"=>"assets/images/category-img/pubu14.jpg"),
       array("id"=>'靳翰龙 国画 山水画 水墨写意 清远 黄湾山人 竖幅立轴',"title"=>"￥4900.00","pic"=>"assets/images/category-img/pubu15.jpg"),
       array("id"=>'赵书亭 国画 山水画 水墨写意 大丘 砚农 斗方',"title"=>"￥2400.00","pic"=>"assets/images/category-img/pubu16.jpg"),
       array("id"=>'徐家礼',"title"=>"￥5600.00","pic"=>"assets/images/category-img/pubu17.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥5700.00","pic"=>"assets/images/category-img/pubu18.jpg"),
       array("id"=>'张延东 国画 山水画 水墨写意 步云堂主人 山水 斗方',"title"=>"￥1900.00","pic"=>"assets/images/category-img/pubu19.jpg"),
       array("id"=>'赵书亭 国画 山水画 水墨写意 大丘 砚农 农舍 斗方',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu20.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 桂林山水 斗方',"title"=>"￥3500.00","pic"=>"assets/images/category-img/pubu21.jpg"),
       array("id"=>'梁冠英 国画 山水画 水墨写意 钰茗阁主 瀑布 树木 横幅',"title"=>"￥6400.00","pic"=>"assets/images/category-img/pubu22.jpg"),
       array("id"=>'刘显辰 国画 山水画 水墨写意 青绿山水 斗方',"title"=>"￥3000.00","pic"=>"assets/images/category-img/pubu23.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥2400.00","pic"=>"assets/images/category-img/pubu24.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥4000.00","pic"=>"assets/images/category-img/pubu25.jpg"),
       array("id"=>'袁海青 国画 山水画 水墨写意 农舍 瑞雪 斗方',"title"=>"￥7600.00","pic"=>"assets/images/category-img/pubu26.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥8200.00","pic"=>"assets/images/category-img/pubu27.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu28.jpg"),
        array("id"=>'靳翰龙 国画 山水画 水墨写意 清远 黄湾山人 竖幅立轴',"title"=>"￥52000.00","pic"=>"assets/images/category-img/pubu29.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 房屋 斗方',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu30.jpg"),
       array("id"=>'徐家礼',"title"=>"￥8200.00","pic"=>"assets/images/category-img/pubu31.jpg"),
       array("id"=>'贾少波 国画 山水画 水墨写意 山水 树木 房屋 斗方',"title"=>"￥6000.00","pic"=>"assets/images/category-img/pubu32.jpg"),
       array("id"=>'梁冠英 国画 山水画 水墨写意 钰茗阁主 山清水秀 田园 横幅',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu1.jpg"),
       array("id"=>'邹湘溪 国画 山水画 水墨写意 雪 斗方',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu2.jpg"),
       array("id"=>'靳翰龙 国画 山水画 水墨写意 清远 黄湾山人 骆驼 横幅',"title"=>"￥22400.00","pic"=>"assets/images/category-img/pubu3.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu4.jpg"),
       array("id"=>'刘粱经 国画 山水画 水墨写意 集云堂主人 山水 树木 房屋 斗方',"title"=>"￥24000.00","pic"=>"assets/images/category-img/pubu5.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥12000.00","pic"=>"assets/images/category-img/pubu6.jpg"),
       array("id"=>'刘粱经 国画 山水画 水墨写意 集云堂主人 山水 树木 房屋 斗方',"title"=>"￥52000.00","pic"=>"assets/images/category-img/pubu7.jpg"),
       array("id"=>'刘显辰 国画 山水画 水墨写意 青绿山水 人物 斗方',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu8.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 房屋 桥 斗方',"title"=>"￥20000.00","pic"=>"assets/images/category-img/pubu9.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥10000.00","pic"=>"assets/images/category-img/pubu10.jpg"),
       array("id"=>'吴延风',"title"=>"￥4900.00","pic"=>"assets/images/category-img/pubu11.jpg"),
       array("id"=>'张平 国画 山水画 水墨写意 山水 树木 横幅',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu12.jpg"),
       array("id"=>'梁冠英 国画 山水画 水墨写意 钰茗阁主 山清水秀 田园 横幅',"title"=>"￥4800.00","pic"=>"assets/images/category-img/pubu13.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥4000.00","pic"=>"assets/images/category-img/pubu25.jpg"),
       array("id"=>'袁海青 国画 山水画 水墨写意 农舍 瑞雪 斗方',"title"=>"￥7600.00","pic"=>"assets/images/category-img/pubu26.jpg"),
       array("id"=>'刘革法 国画 山水画 水墨写意 泽钧 锳世 心斋轩子 山水 树木 房屋 斗方',"title"=>"￥8200.00","pic"=>"assets/images/category-img/pubu27.jpg")
  ];
  $offset = ($page-1)*12; 
  $length = 12;
  echo json_encode(array_slice($arr,$offset,$length));
?>